
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 22 01:35:42 IST 2012
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 16;
  public static final int LCBR = 20;
  public static final int LTE = 7;
  public static final int UMINUS = 14;
  public static final int INTEGER = 49;
  public static final int SEMI = 24;
  public static final int CONTINUE = 34;
  public static final int INT = 37;
  public static final int MINUS = 13;
  public static final int STATIC = 29;
  public static final int LT = 4;
  public static final int LP = 18;
  public static final int COMMA = 25;
  public static final int CLASS = 27;
  public static final int RP = 19;
  public static final int PLUS = 12;
  public static final int MULTIPLY = 15;
  public static final int QUOTE = 48;
  public static final int ASSIGN = 2;
  public static final int IF = 31;
  public static final int THIS = 41;
  public static final int ID = 46;
  public static final int DOT = 26;
  public static final int BOOLEAN = 36;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int RCBR = 21;
  public static final int LB = 22;
  public static final int LAND = 10;
  public static final int EQUAL = 6;
  public static final int TRUE = 44;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int RB = 23;
  public static final int LOR = 11;
  public static final int NULL = 45;
  public static final int MOD = 17;
  public static final int BREAK = 35;
  public static final int VOID = 30;
  public static final int GTE = 8;
  public static final int ELSE = 32;
  public static final int WHILE = 33;
  public static final int NEQUAL = 9;
  public static final int CLASS_ID = 47;
  public static final int EXTENDS = 28;
  public static final int STRING = 42;
  public static final int LNEG = 5;
  public static final int FALSE = 43;
  public static final int GT = 3;
  public static final int LENGTH = 38;
}

